# Generated by Django 4.2.13 on 2024-07-23 13:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='profile_pic', max_length=255, verbose_name='image'),
        ),
    ]
