name: Keep Alive

on:
  schedule:
    - cron: '0 12 * * *'  # runs every day at noon

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping site
        run: curl https://kayak-blog-pp4.onrender.com
